### ISSUE TITLE
Criar diagramas dos ambientes relacionais e dimensionais

### ISSUE THREAD

**Issue by guilherme-savio** [guilherme-savio/seguro-imoveis#3]
O diagrama do ambiente relacional pode ser encontrado aqui: [https://github.com/higorgoulart/SeguroImoveis/blob/main/modelo_fisico/er_diagram.png](url)

**Comment by GabrielSouzaDG** [comment]
Criados os diagramas do modelo relacional e dimensional e incluídos no ReadMe.
