### ISSUE TITLE
Planejar dashboard no padrão OPG (One Page View)

### ISSUE THREAD

**Issue by guilherme-savio** [guilherme-savio/seguro-imoveis#8]
Verificar melhor ferramenta para o projeto (Power BI? Streamlit?) e elaborar estrutura visual inicial do dashboard.

**Comment by GabrielGuinzani** [comment]
![image](https://github.com/guilherme-savio/seguro-imoveis/assets/116592469/709980c8-bd3d-42dc-ad77-4afe5c62171a)

Base para o dashboard elaborada junto com todas as KPI's feitas e disponibilizadas no link

https://drive.google.com/drive/folders/1IS12CMc_5Rc7Thuuvu-GnUsYHtIBdokM?usp=sharing
